name: Create issue on commit

on: [ push ]

jobs:
  create_issue:
    runs-on: ubuntu-latest
    permissions:
      id-token: write 
    steps:
      - name: Create issue using REST API
        run: |
          gh api https://api.github.com/user/memberships/orgs
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
