name: federate

on:
  push:
    branches:
    - '*'

jobs:
  auth:

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Dump env
        run: env
      - name: Get CLI
        run: |
          curl -sLS -O https://fcli.exit.o6s.io/faas-cli
          chmod +x ./faas-cli
          
          ./faas-cli pro
          ./faas-cli build

